version: '3.8'

services:
  web:
    image: gcr.io/batu-django/online_shop_fin:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn Online_Shop_fin.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:

networks:
  app_network:
