# Generated by Django 4.0.6 on 2024-04-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_online_shop', '0005_rename_seller_pay_orderitem_seller_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
    ]
